export const CommentTypes={
    GET_ALL_COMMENTS: 'GET_ALL_COMMENTS',
    ADD_COMMENT: 'ADD_COMMENT',
    REMOVE_COMMENT: 'REMOVE_COMMENT',
}

export const CommentRequestTypes={
    GET_ALL_COMMENT_REQUEST: 'GET_ALL_COMMENT_REQUEST',
    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
    REMOVE_COMMENT_REQUEST: 'REMOVE_COMMENT_REQUEST',
}