export const ProjectTypes={
   GET_CATEGORY: 'GET_CATEGORY',
   GET_ALL_PROJECT:'GET_ALL_PROJECT',
   CREATE_PROJECT: 'CREATE_PROJECT',
   SET_SUBMIT_EDIT_PROJECT: 'SET_SUBMIT_EDIT_PROJECT',
   SET_PROJECT_EDIT: 'SET_PROJECT_EDIT',
   ASSIGN_USER_PROJECT: 'ASSIGN_USER_PROJECT',
   GET_PROJECT_DETAIL: 'GET_PROJECT_DETAIL',
}

export const ProjectRequestTypes={
    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_ALL_PROJECT_REQUEST: 'GET_ALL_PROJECT_REQUEST',
    CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
    UPDATE_PROJECT_REQUEST: 'UPDATE_PROJECT_REQUEST',
    DELETE_PROJECT_REQUEST: 'DELETE_PROJECT_REQUEST',
    ASSIGN_USER_PROJECT_REQUEST: 'ASSIGN_USER_PROJECT_REQUEST',
    REMOVE_USER_FROM_PROJECT_REQUEST: 'REMOVE_USER_FROM_PROJECT_REQUEST',
    GET_PROJECT_DETAIL_REQUEST: 'GET_PROJECT_DETAIL_REQUEST',
}