export const TaskTypes={
    GET_ALL_TASK_TYPE: 'GET_ALL_TASK_TYPE',
    GET_TASK_BY_ID: 'GET_TASK_BY_ID',
    CHANGE_VALUE_TASK_DETAIL: 'CHANGE_VALUE_TASK_DETAIL',
    CHANG_ASSIGNESS:'CHANG_ASSIGNESS',
    REMOVE_USER_ASSIGN:'REMOVE_USER_ASSIGN',
}

export const TaskRequestTypes={
    GET_ALL_TASK_TYPE_REQUEST: 'GET_ALL_TASK_TYPE_REQUEST',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    GET_TASK_BY_ID_REQUEST: 'GET_TASK_BY_ID_REQUEST',
    REMOVE_TASK_BY_ID_REQUEST: 'REMOVE_TASK_BY_ID_REQUEST',
    UPDATE_STATUS:'UPDATE_STATUS'

}