export const userTypes={
    SIGNIN:'SIGNIN',
    SIGNUP: 'SIGNUP',
    LOGOUT:'LOGOUT',
    GET_USERS:'GET_USERS',
}

export const userRequestTypes={
    SIGNIN_REQUEST:'SIGNIN_REQUEST',
    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    GET_USERS_REQUEST:'GET_USERS_REQUEST',
    GET_USER_BY_PROJECT_REQUEST: 'GET_USER_BY_PROJECT_REQUEST',
}